in this directory

D:\Projectts 2026\SANO IRENE\New folder (2), 


i have project gps tracking system, 


D:\Projectts 2026\SANO IRENE\New folder (2)\esp32_Codeess\esp32_v3_1_final.ino


with the picture i attached, it shows in live map, the online/offline shows that device is online and there is communication btn device and server, and gps, 


idle and active status, idlle have to be shown when vehicle is stationary or it is less than 2km/h, but it have also gps have to send coordinates every 2 secs, and for active device is moving with speed great then 2 km/hr. 

also lock and unlock are for relay, to lock vehicle, 


for now those they have to work independenlty like this,

remove errors, like when i lock vehicle then it shows me offline, and for me i sent coomand for locking relay not full device, 


Also i'm moving but ut still shows idlle while i have more speed and moving, also it is showing somtimes offline, while i know devoce is online, 

also in the vehcle there is button to update vehicle but after editing all things it doesn't work and save changes


